-- CreateEnum
CREATE TYPE "RegistrationIntentStatus" AS ENUM ('PENDING', 'COMPLETED');

-- CreateEnum
CREATE TYPE "ConsentType" AS ENUM ('TERMS_ACCEPTED', 'PRIVACY_ACCEPTED', 'MARKETING_GRANTED', 'MARKETING_REVOKED');

-- CreateTable
CREATE TABLE "public_registration_intent" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "status" "RegistrationIntentStatus" NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),

    CONSTRAINT "public_registration_intent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_profile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "customerCode" TEXT NOT NULL,
    "phone" TEXT,
    "documentType" TEXT,
    "documentNumber" TEXT,
    "birthDate" TIMESTAMP(3),
    "marketingConsent" BOOLEAN NOT NULL DEFAULT false,
    "marketingConsentAt" TIMESTAMP(3),
    "termsAcceptedAt" TIMESTAMP(3) NOT NULL,
    "termsVersion" TEXT NOT NULL,
    "privacyAcceptedAt" TIMESTAMP(3) NOT NULL,
    "privacyVersion" TEXT NOT NULL,
    "legacySource" TEXT,
    "legacyId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "customer_profile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_consent" (
    "id" TEXT NOT NULL,
    "customerProfileId" TEXT NOT NULL,
    "consentType" "ConsentType" NOT NULL,
    "granted" BOOLEAN NOT NULL,
    "policyVersion" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "metadata" JSONB,

    CONSTRAINT "customer_consent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "public_registration_intent_userId_key" ON "public_registration_intent"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "customer_profile_userId_key" ON "customer_profile"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "customer_profile_customerCode_key" ON "customer_profile"("customerCode");

-- CreateIndex
CREATE UNIQUE INDEX "customer_profile_legacySource_legacyId_key" ON "customer_profile"("legacySource", "legacyId");

-- CreateIndex
CREATE INDEX "customer_consent_customerProfileId_consentType_idx" ON "customer_consent"("customerProfileId", "consentType");

-- AddForeignKey
ALTER TABLE "public_registration_intent" ADD CONSTRAINT "public_registration_intent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_profile" ADD CONSTRAINT "customer_profile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "customer_consent" ADD CONSTRAINT "customer_consent_customerProfileId_fkey" FOREIGN KEY ("customerProfileId") REFERENCES "customer_profile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================================================
-- Hand-written addition — not generated by `prisma migrate dev`. See
-- DATABASE.md "Append-only enforcement" and ADR-2/ADR-3. Reuses the
-- prevent_update_delete() function created by the first migration
-- (20260728001747_init_foundation_catalog_inventory) — no new function
-- needed, just one more trigger on top of it. Table/column names verified
-- against the CreateTable statement above before pasting.
-- ============================================================================

-- AppendOnly: customer_consent — the durable consent/legal-acceptance
-- ledger must never be edited or deleted after the fact, same as
-- inventory_movement/audit_log.
CREATE TRIGGER customer_consent_append_only
  BEFORE UPDATE OR DELETE ON customer_consent
  FOR EACH ROW EXECUTE FUNCTION prevent_update_delete();
